[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python_anesthesia_simulator"
version = "0.0.1"
authors = [
  { name="Bob Aubouin--Pairault", email="author@example.com" },
]
description = "Python version of an anesthesia simlator."
readme = "README.md"
requires-python = ">=3.9"
dependencies=[
    "numpy==1.22.3",
    "control==0.9.3.post2",
    "scipy==1.7.3",
    "matplotlib==3.5.2"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/BobAubouin/Python_Anesthesia_Simulator"
"Bug Tracker" = "https://github.com/BobAubouin/Python_Anesthesia_Simulator/issues"
